name = "markdown-codelabs-converter"
compatibility_date = "2024-01-01"
main = "src/index.js"

# Cloudflare D1 数据库绑定
[[d1_databases]]
binding = "DB"
database_name = "codelabs-db"
database_id = "e6fd4ddb-34ed-4ab6-9b4f-5573a123951a"

# 环境变量
[vars]
ALLOWED_PREFIX = "https://raw.githubusercontent.com/pub-code"

# 本地开发配置
[env.dev]
name = "markdown-codelabs-converter-dev"
